#!/bin/sh -e

# Removes non-free files from the source tree. Must be done before
# creating the orig.tar.gz.

TOPLEVEL="$1"

if [ "$TOPLEVEL" = "" ]; then
	echo "Please provide the toplevel directory as the argument."
	exit 1
else
	rm -f $TOPLEVEL/kioslave/sieve/draft-murchison-sieve-subaddress-05.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-murchison-sieve-regex-06.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-degener-sieve-editheader.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-martin-managesieve-04.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-homme-sieve-variables.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-degener-sieve-multiscript.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-showalter-sieve-vacation-04.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-daboo-sieve-spamtest.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-melnikov-sieve-imapflags.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-martin-sieve-notify-01.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-degener-sieve-body-00.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-daboo-sieve-include.txt
	rm -f $TOPLEVEL/kioslave/sieve/draft-degener-sieve-copy.txt
fi

exit 0
